name: Benchmark

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bench-dnstaptcp:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/setup-go@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - uses: actions/checkout@v3
      with:
        path: app

    - uses: actions/checkout@v3
      with:
        repository: dmachard/go-dnstap-generator
        path: gen

    - name: Build
      run: |
        cd app/
        go build .
        cd ../gen/
        go build .

    - name: Loading testing
      run: |
        cd app/
        sudo python3 -m unittest tests.bench -v