name: Code checking

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  codechecking:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v2
      with:
        go-version: '1.19'

    - name: gofmt
      run: gofmt -d -e .

    #- name: golint
    #  run: |
    #    sudo apt install golint
    #    golint dnscollector.go
    #    golint loggers/
    #    golint collectors/
    #    golint dnsutils/
    #    golint subprocessors/